arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.g.dart
synthetic-package: false
output-dir: lib/l10n/generated
untranslated-messages-file: untranslated.txt
format: